export {default as HomeScreen} from '../home/HomeScreen'
export {default as ProfileScreen} from '../profile/ProfileScreen'
export {default as SearchScreen} from '../search/SearchScreen'
export {default as NewsScreen} from '../news/NewsScreen'
export {default as OurProud} from '../ourProud/OurProudScreen'
