export default {
    HOME: 'TabRoutes',
    LOGIN: 'LoginScreen',
    REGISTER: 'RegisterScreen',
    FORGOT: 'ForgotPasswordScreen',
    OTPSCREEN: 'OtpScreen',
    RESETPASSWORD: 'ResetPassword',
    GALLERY: 'Gallery',
    NOTIFICATIONS: 'Notifications',
    MYPROFILE: 'MyProfile',
    EVENTS: 'Events',
    REGISTRATIONFORM: 'RegistrationForm',
    SEARCH: 'Search',
    NEWS: 'News',
    OURPROUD: 'OurProud',
    DIRECTORYLISTS: 'DirectoryLists',
    DIRECTORYCONTACTS: 'DirectoryContacts',
    REFERRAL: 'Referral',
    REFERRALLIST: 'ReferralList',
    ADDCONTACTTOCIRECTORY: 'AddContactToDirectory',
    ADDNEWS: 'AddNews',
    MYCONTACTS: 'MyContacts',
    MYNEWS: 'MyNews',
    EDITNEWS: 'EditNews',
    CHANGEPASSWORD: 'ChangePassword',
    FAQ: 'Faq',
    TERMS: 'Terms',
    NEWSDETAILS: 'NewsDetails',
    EDITPROFILE: 'EditProfile',
    BUSINESSDATA: 'BusinessData',
    ALLBUSINESSLIST: 'AllBusinessList',
    SEARCHSCREEN: 'SearchScreen',
    SUGGESTION: 'Suggestion',
    ABOUT: 'About',
  };
  